#Requires -Version 5.1
<#
.SYNOPSIS
    One-click setup for the Day Trading Agent bot package.

.DESCRIPTION
    Installs dependencies, configures API keys, optionally tunes risk settings,
    runs validation tests, and prepares the bot for paper or live trading.
#>

$ErrorActionPreference = "Stop"
$ProjectRoot = $PSScriptRoot

function Write-Step([string]$Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Ok([string]$Message) {
    Write-Host "  [OK] $Message" -ForegroundColor Green
}

function Write-Warn([string]$Message) {
    Write-Host "  [!] $Message" -ForegroundColor Yellow
}

function Write-Fail([string]$Message) {
    Write-Host "  [X] $Message" -ForegroundColor Red
}

function Test-Python {
    Write-Step "Checking Python"
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) {
        Write-Fail "Python not found. Install Python 3.12+ from https://python.org"
        exit 1
    }

    $version = python --version 2>&1
    Write-Ok $version

    if ($version -notmatch "Python 3\.(1[2-9]|[2-9][0-9])") {
        Write-Warn "Python 3.12+ recommended. Setup will continue, but issues are possible."
    }
}

function Install-Dependencies {
    Write-Step "Installing dependencies"
    Push-Location $ProjectRoot
    try {
        python -m pip install --upgrade pip | Out-Null
        python -m pip install -r requirements.txt
        if ($LASTEXITCODE -ne 0) { throw "pip install failed" }
        Write-Ok "All packages installed"
    }
    finally {
        Pop-Location
    }
}

function Initialize-EnvFile {
    Write-Step "Configuring broker connection"
    $envPath = Join-Path $ProjectRoot ".env"
    $examplePath = Join-Path $ProjectRoot ".env.example"

    if (-not (Test-Path $examplePath)) {
        Write-Fail ".env.example not found"
        exit 1
    }

    if (Test-Path $envPath) {
        $overwrite = Read-Host ".env already exists. Reconfigure API keys? (y/N)"
        if ($overwrite -notmatch "^[Yy]") {
            Write-Ok "Keeping existing .env"
            return
        }
    }

    Write-Host ""
    Write-Host "  Get free paper trading keys at: https://app.alpaca.markets/" -ForegroundColor DarkGray
    Write-Host "  Dashboard -> Paper Trading -> API Keys" -ForegroundColor DarkGray
    Write-Host ""

    $skipKeys = Read-Host "Configure API keys now? (Y/n)"
    if ($skipKeys -match "^[Nn]") {
        Copy-Item $examplePath $envPath -Force
        Write-Warn ".env created from template. Add keys before live/paper trading."
        return
    }

    $apiKey = Read-Host "Alpaca API Key"
    $secretKey = Read-Host "Alpaca Secret Key" -AsSecureString
    $secretPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secretKey)
    )

    $mode = Read-Host "Trading mode [paper/live] (default: paper)"
    if ([string]::IsNullOrWhiteSpace($mode)) { $mode = "paper" }
    $mode = $mode.ToLower()
    if ($mode -ne "paper" -and $mode -ne "live") {
        Write-Warn "Invalid mode. Defaulting to paper."
        $mode = "paper"
    }

    if ($mode -eq "live") {
        Write-Host ""
        Write-Warn "LIVE mode uses real money. Make sure you have paper-tested first."
        $confirm = Read-Host "Type YES to confirm live trading mode"
        if ($confirm -ne "YES") {
            $mode = "paper"
            Write-Ok "Switched to paper mode"
        }
    }

    @(
        "# Auto-generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')",
        "ALPACA_API_KEY=$apiKey",
        "ALPACA_SECRET_KEY=$secretPlain",
        "TRADING_MODE=$mode"
    ) | Set-Content -Path $envPath -Encoding UTF8

    Write-Ok ".env saved"
}

function Update-RiskSettings {
    Write-Step "Risk settings (optional)"
    $customize = Read-Host "Customize risk settings? (y/N)"
    if ($customize -notmatch "^[Yy]") {
        Write-Ok "Using default risk settings from config/settings.yaml"
        return
    }

    $settingsPath = Join-Path $ProjectRoot "config\settings.yaml"
    $content = Get-Content $settingsPath -Raw

    $positionPct = Read-Host "Max position size % of account (default: 10)"
    if (-not [string]::IsNullOrWhiteSpace($positionPct)) {
        $decimal = [double]$positionPct / 100
        $content = $content -replace "max_position_pct:\s*[\d.]+", ("max_position_pct: {0}" -f $decimal)
    }

    $stopLoss = Read-Host "Stop loss % (default: 1.5)"
    if (-not [string]::IsNullOrWhiteSpace($stopLoss)) {
        $decimal = [double]$stopLoss / 100
        $content = $content -replace "stop_loss_pct:\s*[\d.]+", ("stop_loss_pct: {0}" -f $decimal)
    }

    $takeProfit = Read-Host "Take profit % (default: 3)"
    if (-not [string]::IsNullOrWhiteSpace($takeProfit)) {
        $decimal = [double]$takeProfit / 100
        $content = $content -replace "take_profit_pct:\s*[\d.]+", ("take_profit_pct: {0}" -f $decimal)
    }

    $dailyLoss = Read-Host "Max daily loss % before halt (default: 3)"
    if (-not [string]::IsNullOrWhiteSpace($dailyLoss)) {
        $decimal = [double]$dailyLoss / 100
        $content = $content -replace "max_daily_loss_pct:\s*[\d.]+", ("max_daily_loss_pct: {0}" -f $decimal)
    }

    $watchlistInput = Read-Host "Watchlist comma-separated (blank = keep defaults)"
    if (-not [string]::IsNullOrWhiteSpace($watchlistInput)) {
        $symbols = $watchlistInput.Split(",") | ForEach-Object { $_.Trim().ToUpper() } | Where-Object { $_ }
        $watchlistBlock = "watchlist:`n" + (($symbols | ForEach-Object { "  - $_" }) -join "`n")
        $content = $content -replace "(?s)watchlist:.*?(?=\r?\nstrategy:)", "$watchlistBlock`n"
    }

    Set-Content -Path $settingsPath -Value $content -Encoding UTF8 -NoNewline
    Write-Ok "settings.yaml updated"
}

function Invoke-ValidationTests {
    Write-Step "Running validation tests"
    Push-Location $ProjectRoot
    try {
        Write-Host "  Simulation test..." -ForegroundColor DarkGray
        python -m src.main --simulate
        if ($LASTEXITCODE -ne 0) { throw "Simulation failed" }
        Write-Ok "Simulation passed"

        $envPath = Join-Path $ProjectRoot ".env"
        if (Test-Path $envPath) {
            $envContent = Get-Content $envPath -Raw
            $hasPlaceholder = $envContent -match 'your_paper_api_key'
            $hasApiKey = $envContent -match 'ALPACA_API_KEY=.+'
            if ($hasPlaceholder -or -not $hasApiKey) {
                Write-Warn "Skipping broker test - API keys not configured"
                return
            }

            Write-Host "  Broker connection test..." -ForegroundColor DarkGray
            python -m src.main --dry-run
            if ($LASTEXITCODE -ne 0) { throw "Broker connection failed" }
            Write-Ok "Broker connection passed"
        }
    }
    finally {
        Pop-Location
    }
}

function Write-Summary {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host "  BOT SETUP COMPLETE" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Start paper trading:   .\run.ps1"
    Write-Host "  Check account:         .\run.ps1 -Status"
    Write-Host "  Run simulation:        .\run.ps1 -Simulate"
    Write-Host "  Edit watchlist/risk:   config\settings.yaml"
    Write-Host "  Edit API keys:         .env"
    Write-Host ""
    Write-Host "  Logs:                  logs\agent.log"
    Write-Host ""
    Write-Host "  Disclaimer: This bot is software automation, not financial advice."
    Write-Host "  Paper trade first. Past results do not guarantee future profits."
    Write-Host ""
}

Write-Host ""
Write-Host "  DAY TRADING AGENT - SETUP WIZARD" -ForegroundColor White
Write-Host "  ================================" -ForegroundColor White

Test-Python
Install-Dependencies
Initialize-EnvFile
Update-RiskSettings
Invoke-ValidationTests
Write-Summary